import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { RootState } from 'app/store';


interface Money {
    amount: number,
    currency: String
}
interface Account {
    id: number,
    name: string,
    balance: Money
}


export interface AccountsState {
    accounts: Account[];
    status: 'idle' | 'loading' | 'failed';
}

const initialState: AccountsState = {
    accounts: [],
    status: 'idle'
};

export const loadAccounts = createAsyncThunk(
    'accounts/loadAccounts',
    async () => {
        const response = await fetch('/accounts/list');
        // The value we return becomes the `fulfilled` action payload
        return response.json();
    }
);

export const accountsSlice = createSlice({
    name: 'accounts',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(loadAccounts.pending, (state) => {
                state.status = 'loading';
            })
            .addCase(loadAccounts.fulfilled, (state, action) => {
                state.status = 'idle';
                state.accounts = action.payload;
            })
            .addCase(loadAccounts.rejected, (state) => {
                state.status = 'failed';
            });
    },
});

export const selectAccounts = (state: RootState) => state.accounts.accounts;

export default accountsSlice.reducer;
